name: Make Result

on:
  workflow_dispatch:     # 手動実行用
  push:
    paths:
      - 'run_tests.sh'
      - '.github/workflows/make-result.yml'

permissions:
  contents: write # for commit result.md
  
jobs:
  make-result:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        env:
          TZ: Asia/Tokyo
        run: |
          sudo apt-get update && sudo apt-get install -y \
                gcc \
                pandoc \
                wkhtmltopdf \
                fonts-ipafont \
                fonts-ipaexfont && \
                fc-cache -fv

      - name: clean md
        run: |
          for folder in $(find . -type f -name '*.c' -exec dirname {} \; | sort -u); do
            if [ -f "$folder/result.md" ]; then
              rm -f "$folder/result.md"
            fi
            touch "$folder/result.md"
            echo "$folder/result.md"
          done
      
      - name: Find and run tests for all .c files and output results in MD by directory
        run: |
          find . -type f -name '*.c' | sort | while read file; do
            folder=$(dirname "$file")
            echo "# $(basename "$file")" >> "$folder/result.md"
            echo "test: $file ($folder) -> $folder/result.md"
            bash test.sh "$file" >> "$folder/result.md" || echo "Error running tests for $file" >> "$folder/result.md"
            echo "" >> "$folder/result.md"
          done
      
      - name: Generate PDF from md
        run: |
          for folder in $(find . -type f -name '*.c' -exec dirname {} \; | sort -u); do
            if [ -f "$folder/result.md" ]; then
              rm -f "$folder/result.pdf"
            fi
            pandoc "$folder/result.md" -o "$folder/result.pdf" --pdf-engine wkhtmltopdf -c style.css -f markdown+emoji --metadata title="$(basename "$folder") 実行結果" 
          done
        continue-on-error: true

      - name: Commit generated md files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add */result.md
          git add */result.pdf
          git commit -m "Update test result md via workflow" || echo "No changes to commit"
          git push origin main
