name: Test All C Files

on:
  workflow_dispatch:     # 手動実行用
  push:
    paths:
      - 'run_tests.sh'
      - '.github/workflows/test-all.yml'

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Find and run tests for all .c files and output results in MD by directory
        run: |
          # 各日付ディレクトリのresult.mdを初期化（例: 0409, 0410）
          for folder in $(find . -maxdepth 1 -type d -name "[0-9][0-9][0-9][0-9]"); do
            rm -f "$folder/result.md"
            touch "$folder/result.md"
          done
          # 各.cファイルについて、親ディレクトリ名を利用し結果を出力
          find . -type f -name '*.c' | while read file; do
            folder=$(basename "$(dirname "$file")")
            echo "# $(basename "$file")" >> "$folder/result.md"
            echo '```' >> "$folder/result.md"
            bash run_tests.sh "$file" >> "$folder/result.md"
            echo '```' >> "$folder/result.md"
            echo "" >> "$folder/result.md"
          done
