name: Test Changed C Files

on:
  push:
    paths:
      - '**/*.c'
      - '**/test/**/*.txt'
      - 'run_tests.sh'
  pull_request:
    paths:
      - '**/*.c'
      - '**/test/**/*.txt'
      - 'run_tests.sh'

jobs:
  test-changed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Get changed C files
        id: changes
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.c$' || true >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run tests on changed files
        run: |
          echo "$CHANGED_FILES" | while read file; do
            if [ -f "$file" ]; then
              echo "🧪 Testing $file ..."
              bash run_tests.sh "$file"
            fi
          done
